package:
    name: analysis_functions_frontiers
    version: 1.0

source:
    git_url: https://github.com/ualsbombe/analysis_functions_frontiers.git

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - analysis_functions_frontiers
